# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Feature-Rich URL Shortner
#+AUTHOR: Lucas Mello Schnorr

#+STARTUP: overview indent
#+LANGUAGE: pt-br
#+OPTIONS: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+OPTIONS: author:nil title:nil date:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_CLASS: ELSEVIER
#+LATEX_CLASS_OPTIONS: [final,12pt]
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{lineno}
#+LATEX_HEADER: \linenumbers
#+LATEX_HEADER: \modulolinenumbers[1]
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{hyperref,xspace}
#+LATEX_HEADER: \usepackage[tight,footnotesize]{subfigure}
#+LATEX_HEADER: \usepackage{tabularx}

# You need at least Org 9 and Emacs 24 to make this work.
# If you do, just type make (thanks Luka Stanisic for this).
# You'll also need to install texlive-publishers to get acmart.cls

* Elsevier configuration for org export + ignore tag (Start Here)  :noexport:

#+begin_src emacs-lisp :results output :session :exports both
(add-to-list 'load-path ".")
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
(add-to-list 'org-latex-classes
             '("ELSEVIER"
               "\\documentclass{elsarticle}"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

#+RESULTS:

* *The Paper*                                                       :ignore:
** Latex configurations                                             :ignore:
#+BEGIN_EXPORT latex
\journal{VIT}
#+END_EXPORT
** Frontpage                                                        :ignore:
*** Authors and Affiliations                                       :ignore:
#+BEGIN_EXPORT latex
%% use the tnoteref command within \title for footnotes;
%% use the tnotetext command for theassociated footnote;
%% use the fnref command within \author or \address for footnotes;
%% use the fntext command for theassociated footnote;
%% use the corref command within \author for corresponding author footnotes;
%% use the cortext command for theassociated footnote;
%% use the ead command for the email address,
%% and the form \ead[url] for the home page:
%% \title{Title\tnoteref{label1}}
%% \tnotetext[label1]{}
%% \author{Name\corref{cor1}\fnref{label2}}
%% \ead{email address}
%% \ead[url]{home page}
%% \fntext[label2]{}
%% \cortext[cor1]{}
%% \address{Address\fnref{label3}}
%% \fntext[label3]{}

\author{Pranav Karande}
\author{Krishyap}
\author{Tejas Mahajan}
\author{Utkarsh Tikkiwal}

\address{
VIT, Vellore Campus, Tiruvalam Rd, Katpadi, Vellore, Tamil Nadu 632014
}
#+END_EXPORT

*** Abstract                                                       :ignore:

#+LaTeX: \begin{abstract}

Put the abstract here.

#+LaTeX: \end{abstract}

*** Graphical Abstract                                             :ignore:

#+latex: %\begin{graphicalabstract}

# Graphical Abstract

#+latex: %\end{graphicalabstract}

*** Research Highlights                                            :ignore:

#+latex: %\begin{highlights}

# \item Research highlight 1
# \item Research highlight 2

#+latex: %\end{highlights}

*** Keywords                                                       :ignore:

#+latex: \begin{keyword}

#+BEGIN_EXPORT latex
%% keywords here, in the form: keyword \sep keyword

%% PACS codes here, in the form: \PACS code \sep code

%% MSC codes here, in the form: \MSC code \sep code
%% or \MSC[2008] code \sep code (2000 is the default)
#+END_EXPORT

#+latex: \end{keyword}
*** Maketitle                                                      :ignore:
#+LaTeX: \maketitle
** Introduction

This is just an example to show how Orgmode can be
neatly used to write papers following the Elsevier latex style. Feel
free to modify and distributed this as you wish.

Be aware that this example is compatible with OrgMode 9.*.

For a detailed explanation on why and how to write reproducible
articles using OrgMode, please visit the following [[https://github.com/alegrand/RR_webinars/blob/master/1_replicable_article_laboratory_notebook/index.org][page]].

** Background and Experimental Context
\label{sec.context}
*** Background
\label{sec.background}
*** Experimental Context and Workload Details
\label{sec.setup}
** Related Work and Motivation
Check this paper about how you need to
semantically aggregate data.

** Your Great Contribution to Computer Science
\label{sec.proposal}
** Your Super Results
** Conclusion
** Acknowledgments                                                  :ignore:

#+LATEX:\section*{Acknowledgements}

Who paid for this?

** References                                                        :ignore:
